# Generated by Django 4.0.2 on 2022-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Electronic', 'Electronic'), ('Sport', 'Sport'), ('Stationary', 'Stationary'), ('Food', 'Food')], max_length=100)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('per_quantity', models.PositiveIntegerField(null=True)),
                ('reorder_level', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
