# Generated by Django 4.0.2 on 2022-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_product_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_in',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_out',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
