# Generated by Django 4.0.2 on 2022-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_product_product_in_product_product_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
